server:
  port: 8080
  servlet:
    context-path: /DLivres
spring:
  datasource:
    password: cegox
    url: jdbc:mysql://localhost:3306/dlivresdb?user=root&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
